Module10 task1
htmlacademy-javascript/1763681-kekstagram-24 pull request #10
Opened 2021-11-08 18:50 UTC by Nara-Safarian

2021-11-08 18:51 UTC, Nara-Safarian commented
10 задание + все задания до конца проекта вместе с дополнительным.

2021-11-09 07:57 UTC, babtshe requested changes

2021-11-09 07:57 UTC, babtshe commented on js/ajax.js
> +}
cм [критерий](https://up.htmlacademy.ru/javascript/24/criteries#d5)

2021-11-09 07:57 UTC, babtshe commented on js/alerts.js
> +      document.addEventListener('keydown', onKeyDown);
точно нужно именно добавить обработчик тут, а не удалить?

2021-11-09 07:57 UTC, babtshe commented on js/alerts.js
> +  }
комплект обработчиков для сообщений об ошибках и успехе практически идентичный. Хорошо бы переписать код так, чтобы не повторяться.

2021-11-09 07:57 UTC, babtshe commented on js/big_picture.js
> +    commentsLoader.onclick = () => {
было бы правильно добавлять обработчики единообразно.

2021-11-09 07:57 UTC, babtshe commented on js/filters.js
> +  filterDiscussed.addEventListener('click', changeActiveFilterDebounced);
обработчики хорошо назвать единообразно по проекту.

2021-11-09 07:57 UTC, babtshe commented on js/form.js
> +const EFFECTS = {
константы идут перед основным кодом.

2021-11-10 09:53 UTC, babtshe approved these changes

2021-11-10 09:53 UTC, merged